### ISSUE TITLE
Miele integration not working at all after exception during restart

### ISSUE THREAD

**Issue by slyoldfox** [astrandb/miele#126]
### The problem

I restart my HA every day at 2:00 (to solve some issues with unix pipe leaks).

Today the miele Integration was totally "offline". It seems there was an exception during the bootup phase.

### Version of miele integration having the issue?

0.0.23

### Version of Home Assistant Core having the issue?

2022.8.6

### Anything in the logs that might be useful for us?

```txt
2022-08-25 02:00:20.518 INFO (MainThread) [homeassistant.components.cover] Setting up cover.smartthings
2022-08-25 02:00:20.518 INFO (MainThread) [homeassistant.components.switch] Setting up switch.smartthings
2022-08-25 02:00:20.518 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.smartthings
2022-08-25 02:00:20.518 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.smartthings
2022-08-25 02:00:20.518 INFO (MainThread) [homeassistant.components.scene] Setting up scene.smartthings

2022-08-25 02:00:33.569 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Miele for miele
Traceback (most recent call last):
  File "/Users/slyoldfox/.homeassistant/custom_components/miele/__init__.py", line 160, in async_setup_entry
    res = await miele_api.request("GET", f"/devices/{serial}/actions")
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/pymiele/pymiele.py", line 49, in request
    return await self.websession.request(
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/Users/slyoldfox/.homeassistant/custom_components/miele/__init__.py", line 159, in async_setup_entry
    async with async_timeout.timeout(10):
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/Users/slyoldfox/homeassistant/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2022-08-25 02:00:33.595 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 23.31s
2022-08-25 02:00:33.595 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2022-08-25 02:00:33.627 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
```

### Additional information

I assume the Miele API may have been offline during bootup (or another network issue was going on).

Is it possible to build a retry mechanism when this occurs, or at least not break completely when the network is untable during bootup?

**Comment by astrandb** [comment]
Thank you for the report.
I am aware that there are situations that lead to unrecoverable errors. I will put this on my todo list.
