### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Ivano62** [astrandb/miele#181]
### The problem

I get this error
2022-12-14 06:35:17.297 ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: 'int' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/miele/__init__.py", line 279, in async_fetch
    flat_result[ent] = dict(flatdict.FlatterDict(result[ent], delimiter="|"))
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
TypeError: 'int' object is not iterable

### Version of miele integration having the issue?

0.1.1

### Version of Home Assistant Core having the issue?

2022.12.5

### Anything in the logs that might be useful for us?

```txt
2022-12-14 06:35:17.297 ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: 'int' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/miele/__init__.py", line 279, in async_fetch
    flat_result[ent] = dict(flatdict.FlatterDict(result[ent], delimiter="|"))
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/usr/local/lib/python3.10/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
TypeError: 'int' object is not iterable
```

**Comment by astrandb** [comment]
Are you getting this all the time or is just a single error? 
It is due to unexpected data from Miele API and should not be causing any trouble except this log..

I have seen it myself once early this morning, but never before as far as I can remember.

**Comment by Ivano62** [comment]
At the moment, it's the first and only time I see this error.
Thanks

**Comment by astrandb** [comment]
OK, I will have a look if the error can be handled in the background and perhaps produce a more user-friendly log entry.
