### ISSUE TITLE
Error in light platform

### ISSUE THREAD

**Issue by aturri** [astrandb/miele#250]
### The problem

Since version 0.1.10 + Homeassistant 2023.4.0 I'm issuing a problem with light platform that does not work. When I interact with the light switch of the coffee machine or in an automation, I experience an AttributeError: 'MieleLight' object has no attribute '_ed'.

### Version of miele integration having the issue?

0.1.10

### Version of Home Assistant Core having the issue?

2023.4.0

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.automation.spegnimento_iris
Source: custom_components/miele/light.py:192
Integration: Automazione (documentation, issues)
First occurred: 08:53:20 (2 occurrences)
Last logged: 08:53:20

Automation xxx: Error executing script. Unexpected error for call_service at pos 1: 'MieleLight' object has no attribute '_ed'
While executing automation automation.xxx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 593, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/miele/light.py", line 192, in async_turn_off
    light_type = AMBIENT_LIGHT if self._ed.key == "ambientlight" else LIGHT
AttributeError: 'MieleLight' object has no attribute '_ed'
```

**Comment by astrandb** [comment]
Sorry for that regression. Fix is underway.

**Comment by aturri** [comment]
No problem :) Thank you for quick fix.
