### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by purcell-lab** [astrandb/miele#356]
### The problem

I think I lost wifi connection, which could be handled gracefully as a warning.

I am seeing a KeyError every minute in the logs.

### Version of miele integration having the issue?

0.1.16

### Version of Home Assistant Core having the issue?

2023.11.0

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:347
Integration: Miele (documentation, issues)
First occurred: 12:41:57 PM (383 occurrences)
Last logged: 7:06:08 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/miele/__init__.py", line 222, in _callback_update_actions
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 416, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 783, in _async_generate_attributes
    available = self.available  # only call self.available once per update cycle
                ^^^^^^^^^^^^^^
  File "/config/custom_components/miele/binary_sensor.py", line 347, in available
    return self.coordinator.data[self._ent]["state|status|value_raw"] != 255
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '000176598390'
```

### Additional information

Still new setting up this integration, so there maybe some user error.

It appears that 'normal' operation mode is either Off or Running, but during this key error period it reported On.
![Screenshot 2023-11-02 20 07 54](https://github.com/astrandb/miele/assets/79175134/c0593c7f-f2b3-4f0d-9548-45d9f0d356e7)

![Screenshot 2023-11-02 20 07 59](https://github.com/astrandb/miele/assets/79175134/2fba78bf-4f9a-4583-8eff-dff188e98121)

I have repaired wifi and integration appears to be back to normal.

**Comment by astrandb** [comment]
This KeyError is an odd error that I dont think has been reported before. We report the dada we get from the API and generally avoid to interpret or modify it. In this case the push data from the Miele cloud suddenly stopped to report data from device "000176598390". I have not seen that happen before. The integration should recover when data comes back which I beleive it did. 

The status value is displayed as received and there is not much we can (or should?) do about it.

Let keep this issue open and see if it is possible to filter out the error condition.
