### ISSUE TITLE
Setup failed for custom integration 'miele': Unable to import component: No module named 'flatdict'

### ISSUE THREAD

**Issue by WyriHaximus** [astrandb/miele#570]
### The problem

Integration doesn't start

### Version of miele integration having the issue?

v2024.8.1

### Version of Home Assistant Core having the issue?

2024.10.3

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 19:34:07 (1 occurrences)
Last logged: 19:34:07

Setup failed for custom integration 'miele': Unable to import component: No module named 'flatdict'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/miele/__init__.py", line 13, in <module>
    import flatdict
ModuleNotFoundError: No module named 'flatdict'
```

**Comment by WyriHaximus** [comment]
> Same problem has been reported recently, though it works for many thousands of users. 

Whoops did I miss an existing issue?

> Is this a new install of the integration? 

Existing install but upgraded HA

> How are you running HA? HAOS, docker, core venv?

Kubernetes so Docker

**Comment by astrandb** [comment]
Please see #568 
It seems to be a problem with loading flatdict module in certain docker environments. Are there any errors or logs regarding flatdict when setting up the container? It is sometimes done in the container before you start HA.

**Comment by WyriHaximus** [comment]
> It seems to be a problem with loading flatdict module in certain docker environments. Are there any errors or logs regarding flatdict when setting up the container? It is sometimes done in the container before you start HA.

Haven't found anything yet in the logs besides what I shared. Did find flatdict in the deps directory so it is there. Will dig deeper into the logs

**Comment by astrandb** [comment]
You can add these lines to your config/configuration.yaml and see if anything more is revealed.
```yaml
logger:
    default: info
    logs:
        custom_components.miele: debug
        pymiele: debug
```

**Comment by WyriHaximus** [comment]
Just rolled that out, the only things now I can find now are:

```
2024-10-23 22:12:00.250 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of flatdict==4.0.1
2024-10-23 22:12:08.819 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of pymiele==0.1.7
```

**Comment by astrandb** [comment]
Do you still get the stack trace as above?

**Comment by WyriHaximus** [comment]
Yes that is still there

**Comment by WyriHaximus** [comment]
Thanks for the suggestion @jeanmoulart. Tried that, also removed the integration and both flatdict and pymiele from deps but essentially the same issue persists even tho HA will install both packages. The error is now just: 
```
2024-10-30 21:08:36.912 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration miele: No module named 'flatdict'
```

**Comment by astrandb** [comment]
I have seen in the logs when building and starting HA in my development container that flatdict, and a few other libraries not related to this integration, are built as wheels. To me this indicates that the wheels binary package is not prebuilt in the distribution. It works for the absolute majority of users and I have no real clue what is missing in your setup.

**Comment by WyriHaximus** [comment]
FWIW these are the install outputs:
![image](https://github.com/user-attachments/assets/82691d64-68e1-4f9a-a318-9afd511c98d5)
![image](https://github.com/user-attachments/assets/6a683b90-d201-4472-ba95-c153f4aecf53)
(The flatdict version also seems off tho.)

> I have seen in the logs when building and starting HA in my development container that flatdict, and a few other libraries not related to this integration, are built as wheels. To me this indicates that the wheels binary package is not prebuilt in the distribution. It works for the absolute majority of users and I have no real clue what is missing in your setup.

Is there a way to add the wheels package? IIRC the only thing I've been doing is update the docker image to whichever is the newest, and update packages when HACS tells me a new version is out.

**Comment by astrandb** [comment]
I have tried to install miele in a fresh HA container without any problems - everything works as expected.
Please try these commands and return the output.

```bash
# Access the container
docker exec -it homeassistant /bin/bash
# Show python version
python3 --version
#Show your installed flatdict version, if any...
pip show flatdict
#Uninstall flatdict
pip uninstall flatdict
# Install the required version manually
pip install flatdict==4.0.1
```
Restart HA and install Miele integration.

**Comment by astrandb** [comment]
This problem is not caused by this integration. It is obviously something wrong with the way requirements are loaded for custom_components. 
I know that there has been recent changes from pip to uv for loading and managing such requirements. There are also spurious reports from other integrations about similar problems.
I suggest that you ask in the Discord chat. Here is a link to a similar issue: https://discord.com/channels/330944238910963714/554842238073700352/1305373492245565460

**Comment by WyriHaximus** [comment]
> This problem is not caused by this integration. It is obviously something wrong with the way requirements are loaded for custom_components. 

Agreed, and it's a nasty breaking change. Especially since HA is supposed to manage this for us.

> I know that there has been recent changes from pip to uv for loading and managing such requirements. There are also spurious reports from other integrations about similar problems. 

Having a similar issue with flightradar24 ye.

> I suggest that you ask in the Discord chat. Here is a link to a similar issue: https://discord.com/channels/330944238910963714/554842238073700352/1305373492245565460

Thanks, I will have a look 👍 . 

Do you prefer to keep this open until it's resolved at the root cause (assuming pip vs uv) or just close it?

**Comment by WyriHaximus** [comment]
Seems they fixed something in the first major release of 2025, just upgraded to .2 and both this and the flight radar integrations just worked again

**Comment by Saxin** [comment]
Same issue here, installed the integration via. HACS 4 days ago on Core 2025.1.2, everything worked for 4 days.
Running on x64, Debian 12 Host, Docker container + Supervisor (if that matters)

Today was greeted by those errors: 

**Logger: homeassistant.util.package
Source: util/package.py:159
First occurred: 9:28:47 PM (6 occurrences)
Last logged: 9:30:10 PM**

**Unable to install package flatdict==4.0.1: error: Failed to fetch: `https://files.pythonhosted.org/packages/3e/0d/424de6e5612f1399ff69bf86500d6a62ff0a4843979701ae97f120c7f1fe/flatdict-4.0.1.tar.gz` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/3e/0d/424de6e5612f1399ff69bf86500d6a62ff0a4843979701ae97f120c7f1fe/flatdict-4.0.1.tar.gz) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve
Unable to install package pymiele==0.2.0: error: Failed to fetch: `https://files.pythonhosted.org/packages/31/32/a6d8908c125363399c0413d1d039a653277cf9de47ff562f124c5aad3eab/pymiele-0.2.0-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/31/32/a6d8908c125363399c0413d1d039a653277cf9de47ff562f124c5aad3eab/pymiele-0.2.0-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve`**

Installed both packages inside the container, HA restart and it works again....
Not sure what caused that... strange error message "dns error"
