### ISSUE TITLE
"Power on/off" switch not working on dishwasher

### ISSUE THREAD

**Issue by mundschenk-at** [astrandb/miele#67]
### The problem

The "power on/off" switch does not work for my dishwasher - I got a 400 error in the logs (malformed request according to the API documentation, but unfortunately it has already rotated out by now). I've attached the logs for ”power off", though.

### Version of miele integration having the issue?

miele-0.0.17

### Version of Home Assistant Core having the issue?

core-2022.3.3

### Anything in the logs that might be useful for us?

```
2022-03-11 23:07:23 DEBUG (MainThread) [custom_components.miele.switch] turn_off -> kwargs: {}
2022-03-11 23:07:23 ERROR (MainThread) [custom_components.miele.switch] Turn_off: 400 - Bad Request
```

**Comment by astrandb** [comment]
There is no easy solution to this problem. The integration is sending the command to the API irrespective of if the API is expected to accept it or not. It is the same thing that happens if you just send the command with Swagger without checking all relevant preconditions.
We can avoid the error message by checking the relevant state and suppress the actual API call if preconditions are not met. 
But I am not sure it will be perfect anyway. My freezer and fridge signals that they accept powerOff. The API accepts the command but nothing happens on the device.  

I would appreciate if you could catch a diagnostic download on the device just before you toggle the switch so we can see what the API says it will accept in that moment.

**Comment by mundschenk-at** [comment]
I initially thought it's the API state when unsuccessfully trying to switch _on_ the device. I'm less sure now that I've gotten the same error when trying to switch it _off_. I had switched on the dishwasher by opening the door. I'll try that again with Swagger.

**Comment by mundschenk-at** [comment]
OK, I've experimented with Swagger and it's indeed the API state/device support. Good news is that the `actions` array does seem to reflect what is actually possible here.

Example when door is open ("switch.power_on" = "on"):
```
    "actions": {
      "processAction": [],
      "light": [],
      "ambientLight": [],
      "startTime": [],
      "ventilationStep": [],
      "programId": [],
      "targetTemperature": [],
      "deviceName": true,
      "powerOn": false,
      "powerOff": false,
      "colors": [],
      "modes": []
    },
```

Example of dishwasher programmed with smart start (again, the switch entity is on):
```
    "actions": {
      "processAction": [],
      "light": [],
      "ambientLight": [],
      "startTime": [],
      "ventilationStep": [],
      "programId": [],
      "targetTemperature": [],
      "deviceName": true,
      "powerOn": false,
      "powerOff": false,
      "colors": [],
      "modes": []
    },
```

Again, the `powerOff` action is not available, but two `processAction`s are (`start` and `stop`, although weirdly I managed to start the program by tapping stop – which looked like ”cancel” - twice in the app).

**Comment by astrandb** [comment]
> I am unsure if switch is the right platform for this and if it wouldn't be better to present a series of button entitities (enabled/disabled depending on actions state).

I agree that `buttons` are probably better representations of `start & stop` process actions,
`Power on/off` is seems to be something else but it is not clear to me what API data we should use as the current state for poweOn. I had to make something up: https://github.com/astrandb/miele/blob/26aec12643fd10508c727bd973b7df4551b6579e/custom_components/miele/switch.py#L177

I will start to work on a button implementation so we test an see what fits best in what situation.
#68

**Comment by astrandb** [comment]
I have pushed a branch "ButtonPlatform". It exposes buttons for Start & Stop according to Miele's capability matrix. No guard yet for availablity as stated in `actions`. Coming soon...
@mundschenk-at can you test this branch?

**Comment by mundschenk-at** [comment]
Sure! Could you create a "pre-release" from it for easy installation?

**Comment by astrandb** [comment]
I have just merged the added button platform. Buttons for `start`, `stop`, `powerOn` and `powerOff` are created for our devices for testing purposes.
If you select `Redownload` in HACS you can download `main`. That is always the head of main branch which includes all merged changes regardless of if it is released or not.

**Comment by mundschenk-at** [comment]
Ah, sure, I didn't realize `main` was available in HACS. (Though creating a pre-release from a branch has the benefit you don't have to merge first, that's why I suggested it.)

**Comment by mundschenk-at** [comment]
Mhm, that didn't seem to work, @astrandb. I am at 743db48b7761438d32115c8d37734de0d993dd18, but no button entities have been created.

**Comment by astrandb** [comment]
Odd. It works fine on my development system, but no buttons appear on my production system.  Something is wrong with HACS. I'll be back...

**Comment by astrandb** [comment]
@mundschenk-at Repeated the redownload of main - and then it worked.
Btw I had forgotten how easy it was to make a release from a branch. Will do that next time.

**Comment by astrandb** [comment]
There might be a problem with using the main branch from HACS. I use a github action to pack all relevant files in a zip archive. This action is triggered every time a release is created and I don't know how HACS  will behave if there is no zip file available.

**Comment by astrandb** [comment]
@mundschenk-at v0.0.18-beta1 released.

**Comment by mundschenk-at** [comment]
```
Logger: homeassistant.components.button
Source: custom_components/miele/button.py:202 
Integration: Taste (documentation, issues) 
First occurred: 17:19:11 (1 occurrences) 
Last logged: 17:19:11

Error while setting up miele platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/miele/button.py", line 166, in async_setup_entry
    MieleButton(
  File "/config/custom_components/miele/button.py", line 202, in __init__
    self._attr_name = f"{self.coordinator.data[self._ent][self.entity_description.type_key]} {self.entity_description.name}"
KeyError: None
```

**Comment by astrandb** [comment]
v0.0.18-beta2 is out!

**Comment by mundschenk-at** [comment]
Looking good so far with the washer dryer (which didn't get a `switch` entity, BTW). The dishwasher is waiting to be unloaded, so I could not try anything there (and it doesn't want to be switched on, as we know).

**Comment by mundschenk-at** [comment]
Looks right for the dishwasher as well, @astrandb.

**Comment by astrandb** [comment]
Sound good!

**Comment by astrandb** [comment]
Sounds good!
I just followed the compatibility matrix - so switch for washer/dryer.
The question to think about is how we should set up the default configuration. In what cases is the switch the best representation and in what cases are buttons better? E. g. a switch is logical for superfreeze on and off in a freezer.

**Comment by mundschenk-at** [comment]
> I just followed the compatibility matrix - so no switch for washer/dryer.

The compatibility matrix is incorrect. In fact, it looks like my dishwasher doesn't support `powerOn`/`powerOff` whereas the washer-dryer does. (It would also seem unlikely that `washer-dryer` deviated from both `washing machine` and `tumble dryer`.)

> The question to think about is how we should set up the default configuration. In what cases is the switch the best representation and in what cases are buttons better? E. g. a switch is logical for superfreeze on and off in a freezer.

Superfreeze sounds logical for a switch, I agree. For devices that really* support `powerOn`/`powerOff` a switch might be OK, though state should be inverse of available actions. If that's not possible, buttons are probably better. 

* Not sure how that could be determined.

**Comment by astrandb** [comment]
I tried to summarize our discussions on the design here: https://github.com/astrandb/miele/wiki 
Will do some cleanup in the code and release within a day or two.

**Comment by mundschenk-at** [comment]
With the latest beta, I have both push buttons and switch entities for power on/off. Is that intentional?

**Comment by astrandb** [comment]
The buttons should be inactive!? They are still defined and can be deleted in the UI and they should then disappear for good. 
I was too lazy to create procedures for clean up after testing different variants between the beta releases.

**Comment by mundschenk-at** [comment]
No, the work in parallel to the `switch` entity, i.e. I can switch the washing machine on using the `switch` entity and switch it off using the `button` entity (or vice-versa).

**Comment by mundschenk-at** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/6943905/158082116-eb6965de-ec62-494e-8cbf-53faa4a387fe.png">

(Haven't renamed the power on/off buttons because I assumed they would be gone.)

**Comment by astrandb** [comment]
My mistake. Forgot to remove these buttons before releasing the beta. New version coming soon. You may need to manually remove the stale buttons from the UI though.
