### ISSUE TITLE
Error Miele

### ISSUE THREAD

**Issue by legantois** [astrandb/miele#92]
### The problem

Receives sometimes this error

last lines are coming from my action to switch on and light on my oven

it disappears at HA restart

My Miele oven
DGC7460
Firmware: 03.88
Hardware: EK037 

### Version of miele integration having the issue?

miele

### Version of Home Assistant Core having the issue?

core-2022.5.3

### Anything in the logs that might be useful for us?

```txt
2022-05-09 09:29:55 ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: 'int' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/miele/__init__.py", line 228, in async_fetch
    flat_result[ent] = dict(flatdict.FlatterDict(result[ent], delimiter="|"))
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
TypeError: 'int' object is not iterable
2022-05-09 09:50:06 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [Connection reset by peer]
2022-05-09 10:21:37 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data
2022-05-09 11:58:54 ERROR (MainThread) [custom_components.miele.light] Turn_on: 500 - Internal Server Error
2022-05-09 11:59:00 ERROR (MainThread) [custom_components.miele.light] Turn_on: 400 - Bad Request
2022-05-09 11:59:08 ERROR (MainThread) [custom_components.miele.switch] Turn_on: 400 - Bad Request
```

**Comment by astrandb** [comment]
Please capture and attach a "Diagnostic download" from the oven device page. Once after restart when everything works and once again when the described error has occurred.

**Comment by legantois** [comment]
[config_entry-miele-af0a8413bcf8571bb9253e8d09d08b51.json.txt](https://github.com/astrandb/miele/files/8650993/config_entry-miele-af0a8413bcf8571bb9253e8d09d08b51.json.txt)

please find diag now, after restart. Will send 2nd file when problem occurs again

**Comment by legantois** [comment]
Same issue this night

log:
2022-05-09 23:24:44 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data
2022-05-09 23:49:38 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data
2022-05-09 23:55:18 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data
2022-05-10 02:48:28 ERROR (MainThread) [custom_components.miele.switch] Turn_on: 400 - Bad Request
2022-05-10 02:48:31 ERROR (MainThread) [custom_components.miele.light] Turn_off: 400 - Bad Request
2022-05-10 06:02:23 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [None]
2022-05-10 06:06:23 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [None]
2022-05-10 06:09:26 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [None]
2022-05-10 06:11:27 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [None]
2022-05-10 06:14:41 ERROR (MainThread) [custom_components.miele] Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)]
2022-05-10 06:17:51 ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: 'int' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/miele/__init__.py", line 228, in async_fetch
    flat_result[ent] = dict(flatdict.FlatterDict(result[ent], delimiter="|"))
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/usr/local/lib/python3.9/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
TypeError: 'int' object is not iterable
2022-05-10 07:22:50 ERROR (MainThread) [custom_components.miele.light] Turn_on: 400 - Bad Request
2022-05-10 07:22:52 ERROR (MainThread) [custom_components.miele.switch] Turn_on: 400 - Bad Request


Diag file

[config_entry-miele-af0a8413bcf8571bb9253e8d09d08b51.json(4).txt](https://github.com/astrandb/miele/files/8657630/config_entry-miele-af0a8413bcf8571bb9253e8d09d08b51.json.4.txt)

**Comment by astrandb** [comment]
The API server at Miele has been unavailable a coupe of times tha last few days. I have seen similar logs in my setup. The error recovery in the integration is not good enough though. I will have a look at it.

**Comment by gigatexel** [comment]
I just had this too, when setting up the component.

Issue is possibly that when the component is set up for the first time and no devices are turned on, there is nothing to set up :-)

Turning on a random Miele appliance and restarting HA might fix the issue.

**Comment by astrandb** [comment]
@gigatexel If the Miele API is behaving properly all registered devices should be created in HA. It should not matter if they are turned on or off.
If you see this again, please do a diagnostic download from the Configuration->Integrations->Miele panel.
